name: build

on:
  push:
  pull_request:

jobs:
  build-qs:
    runs-on: macos-latest
    env:
      QS_SOURCE_ROOT: /tmp/git/quicksilver
      QS_DONT_TEST: 1
      CONFIGURATION: Debug
    steps:
      - run: |
          latest_tag=$(
            git ls-remote --tags --refs --sort="-v:refname" https://github.com/quicksilver/quicksilver |
              awk -F/ '{ print $NF; exit }'
          )
          mkdir -p "${QS_SOURCE_ROOT}"
          git clone --recurse-submodules --branch="${latest_tag}" --depth=1 https://github.com/quicksilver/Quicksilver.git "${QS_SOURCE_ROOT}"

          pushd "${QS_SOURCE_ROOT}/Quicksilver"
          ./Tools/qsrelease Debug

  template-plugin:
    runs-on: macos-latest
    needs: build-qs
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -x

          pwd

          python -m pip install --user cookiecutter

          pushd "$(mktemp -d)"
          python -m cookiecutter \
            --no-input \
            "${OLDPWD}" \
            plugin_name=QSMyPlugin \
            author="Nathan Henrie" \
            description="test plugin for CI"

          pushd QSMyPlugin

          ls -l /private/tmp/QS/Configuration/Debug.xcconfig

          xcodebuild -scheme QSMyPlugin build
          xcodebuild -scheme QSMyPlugin test
